name: flutter_google_places_sdk_linux
description: The linux implementation of Flutter plugin for google places sdk
version: 1.0.5
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_linux

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface:
    git:
      url: git@github.com:crispybaconsrl/flutter_google_places.git
      path: flutter_google_places_sdk_platform_interface
      ref: 1.0.5
#    path: ../flutter_google_places_sdk_platform_interface
  flutter_google_places_sdk_http:
    git:
      url: git@github.com:crispybaconsrl/flutter_google_places.git
      path: flutter_google_places_sdk_http
      ref: 1.0.5
#    path: ../flutter_google_places_sdk_http

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: flutter_google_places_sdk
    platforms:
      linux:
        fileName: flutter_google_places_sdk_linux.dart
        dartPluginClass: FlutterGooglePlacesSdkLinuxPlugin
